require 'rake'
require 'parallel'
require 'rspec/core/rake_task'

RSpec::Core::RakeTask.new(:base_smoke) do |t|
  t.pattern = Dir.glob('spec/smokes/login.smoke.rb')
  t.rspec_opts = '--format documentation'
  t.verbose = false
end

task :smoke_stage do |t, args|
  ENV['CONFIG_NAME'] = "stage"
  ENV['BROWSER_NAME'] = "chrome"
  Rake::Task["base_smoke"].invoke
  Rake::Task["base_smoke"].reenable
end

task :default => :smoke_stage #:chrome

task :smoke_prod do |t, args|
  ENV['CONFIG_NAME'] = "prod"
  ENV['BROWSER_NAME'] = "chrome"
  Rake::Task["base_smoke"].invoke
  Rake::Task["base_smoke"].reenable
end

task :parallel do |t, args|
  @browsers = ['firefox', 'chrome']
  Parallel.map(@browsers, :in_processes => @browsers.length) do |browser|
    ENV['BROWSER_NAME'] = browser
    ENV['CONFIG_NAME'] = "prod"
    Rake::Task["base_smoke"].invoke
    Rake::Task["base_smoke"].reenable
  end
end
