module.exports = {
  '@tags': ['userprofile','smoke'],
  'success change user data': client => {
    const loginPage = client.page.login()
    const myProfile = client.page.myaccount()
    client.resizeWindow(1200, 900)
    loginPage.navigate()
             .waitApp()
             .loginUserSuccess()
    client.assert.urlEquals(`${LINK_TO_RESOURCE}myaccount/account/websites`)
    myProfile.navigate()
             .waitApp()
             .changeUserFirstName('test name')
             .successSubmitUserData()
             .changeUserLasttName('test name')
             .successSubmitUserData()
             .changeUserStreetAddress1('test adr 1')
             .successSubmitUserData()
             .changeUserStreetAddress2('test adr 2')
             .successSubmitUserData()
             .changeCountry('test countr')
             .successSubmitUserData()
    client.end()
  },
  'success change user password': client => {
    const loginPage = client.page.login()
    const myProfile = client.page.myaccount()
    client.resizeWindow(1200, 900)
    loginPage.navigate()
             .waitApp()
             .loginUserSuccess()
    client.assert.urlEquals(`${LINK_TO_RESOURCE}myaccount/account/websites`)
    myProfile.navigate()
             .waitApp()
             .changeUserPasswordSuccess(USER_PASSWORD, USER_PASSWORD)
    client.end()
  },
  'failed change user password': client => {
    const loginPage = client.page.login()
    const myProfile = client.page.myaccount()
    client.resizeWindow(1200, 900)
    loginPage.navigate()
             .waitApp()
             .loginUserSuccess()
    client.assert.urlEquals(`${LINK_TO_RESOURCE}myaccount/account/websites`)
    myProfile.navigate()
             .waitApp()
             .changeUserPasswordFailed(USER_PASSWORD + '1' , USER_PASSWORD)
    client.end()
  }
}